# Generated by Django 3.0.6 on 2020-08-13 15:12

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=stdimage.models.StdImageField(upload_to='fotos', verbose_name='Imagem'),
        ),
    ]
