# Generated by Django 3.0.6 on 2020-08-13 15:24

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200813_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
